### ISSUE TITLE
Missing Dependency chalofa_ruby-progressbar-0.0.9.1

### ISSUE THREAD

**Issue by Bramanga** [lelylan/rest-oauth2-server#38]
~/Projects/rest-oauth2-server$ bundle
Fetching gem metadata from http://rubygems.org/.......
Fetching gem metadata from http://rubygems.org/..
Could not find chalofa_ruby-progressbar-0.0.9.1 in any of the sources

**Comment by fabioberger** [comment]
Any update on this?

**Comment by fabioberger** [comment]
Bramanga, this gem has been yanked. Just go to this URL, download the gem here: 

http://rubygems.org/gems/chalofa_ruby-progressbar and place it in your applications folder. 

Then run: gem install --local ./chalofa_ruby-progressbar-0.0.9.1.gem

And then run bundle install and it should work!

**Comment by Bramanga** [comment]
Yep that worked. Thanks!
